--select * from items order by price
--select * from items where price >= 80 order by price
--select * from customers order by firstname limit 3
--select lastname from customers order by lastname desc
